/* scSCServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.28 from sc.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef scSCServiceSoapBindingProxy_H
#define scSCServiceSoapBindingProxy_H
#include "scH.h"

namespace sc {

class SOAP_CMAC SCServiceSoapBindingProxy
{ public:
	struct soap *soap;
	bool soap_own;
	/// Endpoint URL of service 'SCServiceSoapBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in sc.h (non-static)
	/// Constructor
	SCServiceSoapBindingProxy();
	/// Copy constructor
	SCServiceSoapBindingProxy(const SCServiceSoapBindingProxy& rhs);
	/// Constructor to use/share an engine state
	SCServiceSoapBindingProxy(struct soap*);
	/// Constructor with endpoint URL
	SCServiceSoapBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	SCServiceSoapBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	SCServiceSoapBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	SCServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor deletes non-shared engine context only (use destroy() to delete deserialized data)
	virtual	~SCServiceSoapBindingProxy();
	/// Initializer used by constructors
	virtual	void SCServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Create a new copy
	virtual	SCServiceSoapBindingProxy *copy() SOAP_PURE_VIRTUAL;
	/// Copy assignment
	SCServiceSoapBindingProxy& operator=(const SCServiceSoapBindingProxy&);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'invoke' (returns error code or SOAP_OK)
	virtual	int invoke(std::string _xmlData, std::string &_invokeReturn) { return this->invoke(NULL, NULL, _xmlData, _invokeReturn); }
	virtual	int invoke(const char *endpoint, const char *soap_action, std::string _xmlData, std::string &_invokeReturn);
};

} // namespace sc

#endif
